[package]
name = "onion_earn"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]

[dev-dependencies]

[profile.release]
opt-level = 3
overflow-checks = true
debug = 0
strip = "symbols"
lto = true
panic = "abort"
codegen-units = 1
